# -*- coding: utf-8 -*-
"""AI_chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12wB0_TCrylTUrY88mJ0ymt6ADmUPfW56
"""

pip install nltk

import nltk
nltk.download('punkt')
nltk.download('wordnet')
nltk.download('omw-1.4')  # Required for WordNet Lemmatizer to work

import nltk
import numpy as np
import random
import string
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

nltk.download('wordnet')
nltk.download('omw-1.4')

corpus = """
Hello! I am your AI chatbot.
I can help you with basic queries about Python, AI, and general topics.
Python is a popular programming language.
Artificial Intelligence is a branch of computer science.
NLP stands for Natural Language Processing.
You can use NLTK or spaCy for text processing.
Machine Learning is a part of AI.
How can I help you today?
"""

# ✅ Easy sentence splitting
sent_tokens = corpus.split('.')
sent_tokens = [s.strip() for s in sent_tokens if s.strip()]
lemmer = nltk.stem.WordNetLemmatizer()

def LemTokens(tokens):
    return [lemmer.lemmatize(token.lower()) for token in tokens if token not in string.punctuation]

def LemNormalize(text):
    return LemTokens(nltk.word_tokenize(text.lower()))

GREETING_INPUTS = ("hello", "hi", "hey", "greetings")
GREETING_RESPONSES = ["Hello!", "Hi!", "Hey!", "Hi there!"]

def greeting(sentence):
    for word in sentence.split():
        if word.lower() in GREETING_INPUTS:
            return random.choice(GREETING_RESPONSES)

def generate_response(user_input):
    robo_response = ''
    sent_tokens.append(user_input)

    TfidfVec = TfidfVectorizer(tokenizer=LemNormalize, stop_words='english')
    tfidf = TfidfVec.fit_transform(sent_tokens)

    vals = cosine_similarity(tfidf[-1], tfidf)
    idx = vals.argsort()[0][-2]

    flat = vals.flatten()
    flat.sort()
    req_tfidf = flat[-2]

    if req_tfidf == 0:
        robo_response = "Sorry, I don't understand."
    else:
        robo_response = sent_tokens[idx]

    sent_tokens.pop()
    return robo_response

def chatbot():
    print("Chatbot: Hi! I'm your chatbot. Type 'bye' to exit.")
    while True:
        user_input = input("You: ").lower()
        if user_input == 'bye':
            print("Chatbot: Bye! Have a great day.")
            break
        elif greeting(user_input) is not None:
            print("Chatbot:", greeting(user_input))
        else:
            print("Chatbot:", generate_response(user_input))

chatbot()